EXTRN DEC_UNSIGN: NEAR

CSEG SEGMENT PARA PUBLIC 'CODE'
	ASSUME CS:CSEG
	
	DEC_SIGN PROC NEAR
		PUSH BP
		MOV BP, SP
		MOV BX, [BP + 4]
		MOV AX, [BX] ; AX CONTAINS RAW VALUE
		
		PUSH AX ; SAVING RAW ARGUMENT
		
		CMP AX, 0
		; SIGNED COMPARISON, IF GREATER OR EQUAL => POSITIVE
		JGE POSITIVE; IF VALUE IS POSITIVE,  WE PRINT IT AS AN UNSIGNED
		
		; IF VALUE IS NEGATIVE, WE NEED TO PRINT '-' AND THEN NEGATE IT
		PUSH AX		
		MOV DL, '-'
		MOV AH, 2
		INT 21H
		POP AX
		
		NEG AX
		MOV [BX], AX		
		POSITIVE: 
		
		PUSH BX ; POINTER TO ARGUMENT
		CALL DEC_UNSIGN
		
		POP AX ; RESTORING ORIGINAL ARGUMENT
		MOV [BX], AX
		
		POP BP
		RET 2
	DEC_SIGN ENDP
	
CSEG ENDS

PUBLIC DEC_SIGN

END